In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
(x_train ,y_train), (x_valid, y_valid) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [3]:
x_train.shape

(60000, 28, 28)

In [4]:
x_valid.shape

(10000, 28, 28)

In [5]:
x_train.dtype
#uint8 代表沒有正負號的8位元整數

dtype('uint8')

In [6]:
x_train.min()

0

In [7]:
x_train.max()

255

In [8]:
x_train[0]
#數字越大代表顏色越白

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [9]:
#flatten 28*28 = 784
x_train = x_train.reshape(60000, 784)
x_valid = x_valid.reshape(10000, 784)

In [10]:
x_train[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [11]:
#normailzation
x_train = x_train / 255
x_valid = x_valid / 255

In [12]:
x_train.max()

1.0

In [13]:
x_train[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [14]:
x_train.dtype

dtype('float64')

In [15]:
y_train[0:9]

array([5, 0, 4, 1, 9, 2, 1, 3, 1], dtype=uint8)

In [16]:
# we do one hot encoding
# 建立一個 10 維的向量，因為數字產生的距離差是沒有意義的
# true answer 是第一類，但預測出來是第二類跟預測出來是第三類的loss應該相同

num_categories = 10

y_train = tf.keras.utils.to_categorical(y_train, num_categories)
y_valid = tf.keras.utils.to_categorical(y_valid, num_categories)

In [17]:
y_train[0:9]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [18]:
model = tf.keras.models.Sequential([
        tf.keras.layers.Dense(512, activation= 'relu', input_shape= (784,)),
        tf.keras.layers.Dense(512, activation= 'relu'),
        tf.keras.layers.Dense(10, activation= 'softmax')
])
#做分類問題最後都要進 softmax 把值壓到 0~1 之間才能當作機率

In [24]:
model = keras.Sequential()
model.add(layers.Dense(512, activation= 'relu', input_shape= (784,)))
model.add(layers.Dense(256, activation= 'relu'))
model.add(layers.Dense(128, activation= 'relu'))
model.add(layers.Dense(10, activation= 'softmax'))

In [25]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 512)               401920    
                                                                 
 dense_10 (Dense)            (None, 256)               131328    
                                                                 
 dense_11 (Dense)            (None, 128)               32896     
                                                                 
 dense_12 (Dense)            (None, 10)                1290      
                                                                 
Total params: 567,434
Trainable params: 567,434
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.compile(optimizer= 'adam' ,loss= 'categorical_crossentropy', metrics= ['accuracy'])

In [27]:
history = model.fit(
    x_train, y_train, epochs= 10, verbose= 1, validation_data= (x_valid, y_valid)
)

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1972 - accuracy: 0.9404 - val_loss: 0.1113 - val_accuracy: 0.9653
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0854 - accuracy: 0.9739 - val_loss: 0.0796 - val_accuracy: 0.9747
Epoch 3/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0636 - accuracy: 0.9800 - val_loss: 0.0959 - val_accuracy: 0.9729
Epoch 4/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0480 - accuracy: 0.9851 - val_loss: 0.0878 - val_accuracy: 0.9732
Epoch 5/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0356 - accuracy: 0.9890 - val_loss: 0.0961 - val_accuracy: 0.9767
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0342 - accuracy: 0.9890 - val_loss: 0.0681 - val_accuracy: 0.9812
Epoch 7/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0253 - accuracy: 0.9920 - val_loss: 0.0795 - val_accuracy:

In [28]:
model.evaluate(x_valid, y_valid, verbose= 1)

313/313 [==============================] - 1s 3ms/step - loss: 0.0827 - accuracy: 0.9813


[0.08272437751293182, 0.9812999963760376]

In [29]:
model.save('mnist')

INFO:tensorflow:Assets written to: mnist\assets
